# Application Constants

# Database
DB_TIMEOUT = 30.0

# Network
REQUEST_TIMEOUT_DEFAULT = 10
REQUEST_TIMEOUT_LONG = 30
USER_AGENT = "ThreatFeedAggregator/1.0"

# Scheduling
DEFAULT_SCHEDULE_INTERVAL_MINUTES = 60
DAILY_SCHEDULE_INTERVAL_MINUTES = 1440

# Defaults
DEFAULT_INDICATOR_LIFETIME_DAYS = 30
